config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'mainpage#index'

  resources :genres do
    resources :tracks, only: [:index]
  end
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Genre < ApplicationRecord
  has_many :tracks

  validates :name, presence: :true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  load_and_authorize_resource
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  def index
    @genres = Genre.all
  end

  def show
    @tracks=@genre.tracks
  end

  def new
    @genre = Genre.new
  end


  def edit
  end

  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for(genre) do |f| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="actions">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= button_to 'Back', genres_path, method: 'get' %>

app/views/genres/index.html.erb
<h1>Genres</h1>
<% if can? :create, Genre %>
    <%= button_to 'New Genre', new_genre_path, method: 'get' %>
<% end %>
<div>
  <% @genres.each do |genre| %>
      <div>
        <h5><%= genre.name %></h5>

        <% if can? :read, Genre %>
            <%= link_to 'Show', genre %>
        <% end %>

        <% if can? [:destroy], Genre %>
            <%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
  <% end %>
</div>
<br>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= button_to 'Back', genres_path, method: 'get'%>

app/views/genres/show.html.erb
<% if can? :update, Genre %>
    <%= button_to 'Edit', edit_genre_path(@genre), method: 'get' %>
<% end %>
<%= button_to 'Back to Genres', genres_path, method: 'get' %>

<% @tracks.each do |track| %>
    <h4><%= track.music.original_filename.chomp('.mp3') %></h4>
    <%=audio_tag track.music, controls: true, class: "audio-play"%>
<% end %>